### ISSUE TITLE
UI5-AutomationFramework MAC execution issue 

### ISSUE THREAD

**Issue by Kronnork** [SAP/ui5-automation-framework#3] opened 2018-07-20 04:07 UTC
I am getting the following issue while executing the recorded tests :

script step5:assertion on sap.m.Table
  - Failed: unknown error: sap is not defined
    (Session info: headless chrome=67.0.3396.99)
    (Driver info: chromedriver=2.40.565386 (45a059dc425e08165f9a10324bd1380cc13ca363),platform=Mac OS X 10.13.5 x86_64)

Can we point to the specific runtime library that is missing here ?

**Comment by asifnavalur** [comment] 2018-07-20 04:37
can you share the url and the steps to reach upto step5?

**Comment by Kronnork** [comment] 2018-07-25 11:48
Hi asifnavalur,

The issue comes when we execute the tests in runtime.

Steps for installing runtime is -

a. Created a directory as recommended
b. Goto the Directory and ran the following command -
     npm install --save  https://github.com/SAP/ui5-automation-framework
     It takes around 20 min to install. Shall we work on optimisations. Are you also covering postinstall ?
     Installation was successful but ERROR: Can't find config file: .jshintrc was there.
c. Executing the command for test on runtime 
    cd <path-to-created-folder>/node_modules/ui5-automation-framework/UI5Example
    $ node <path-to-created-folder>/node_modules/ui5-automation-framework/protractor/bin/protractor conf.js

Due to local development we will not be able to share the url. Since we are evaluating the test frameworks, we also see that UI elements are not getting focussed.
This needs to be fixed even if this is an expected or already anticipated issue.

Can you suggest the time frame for the fix?

**Comment by asifnavalur** [comment] 2018-07-25 12:14
As u mentioned tha you are getting this error- " sap is not defined "
Pls open the developer console and type sap.ui   - does it return an object or error?
Regards,
Asif

**Comment by Kronnork** [comment] 2018-07-25 14:16
Hi Asif,

Thanks for the response.
it does return the object.

Does the error during installation  

> ERROR: Can't find config file: .jshintrc

 anything to do with the same?

**Comment by Kronnork** [comment] 2018-07-25 14:20
Also suggest due to inconsistent recording behavior shall we move on to https://openui5.hana.ondemand.com/#/topic/ab134ef3932c4b42898c79c10341e8b5

**Comment by asifnavalur** [comment] 2018-07-25 14:39
Is your application built on UI5? Otherwise it wouldn’t return null

Another way to check
The chrome extension icon color changes to blue or not? If not then your app is not ui5

**Comment by asifnavalur** [comment] 2018-07-25 14:41
Are you able to run the sample ui5 example available in the framework folder?

**Comment by asifnavalur** [comment] 2018-07-25 14:43
I presume your first 4 steps are working and you have problem in 5th step? 
Can you paste only that block

**Comment by Prabal4Lyf** [comment] 2018-07-27 06:11
@Kronnork 
If I understand the issue correctly, then there might be a configuration issue with the authentication part of the conf.js
I also faced the same issue when i did not correctly define the > **formType** in the auth section as follows:
```
 auth: {
          formType:'plain',
        username: 'Testuser',
        password: 'xxxxxxx'
  },

```

The above code will trigger the issue since login pages may not be strictly ui5 pages or fiori based.

Now the formtype can be deduced from the list defined in 
https://github.com/SAP/ui5-automation-framework/blob/master/protractor/built/authConfig.js

or you can define it by adding to the authConfig,js the id elements for username, password and the logon button.

so mostly if you are using scp then it will be closely be the following:

```
 auth: {
          formType:'sapcloud-form',
        username: 'Testuser',
        password: 'xxxxxxx'
  },

```

Kindly confirm to deduce next steps. 

Thanks
Prabal

**Comment by Kronnork** [comment] 2018-07-27 07:15
Solves the issue.
Awesome sauce.. 
Best would be to have it documented... 👍 
Also can we do something about the instability of focusing on the elements or is there a fix already.. ?

Thanks

**Comment by asifnavalur** [comment] 2018-07-27 07:44
Thanks Prabal for figuring this out.
Hope the issue is solved and hence closing.
instability of focusing on the element - I propose you to create a seperate issue
Regards,
Asif

**Closed as completed by asifnavalur** 2018-07-27 07:44 UTC

**Comment by asifnavalur** [comment] 2018-07-27 09:25
@Kronnork - You are invited to contribute in documenting if you think it makes sense

**Comment by Kronnork** [comment] 2018-07-27 16:26
@asifnavalur  
Kindly share your development environment setup guide as the readme only has usage guide.
I want to check if the instability case also.

Add the issue of instability to your known issues since this requires investment. README needs to be updated.
